version: "3.8"

services:
  microservice-db:
    image: mysql:8
    container_name: microservice-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schedule_notification_db
    ports:
      - "${PORT_MICROSERVICE_DB:-3306}:3306"
    networks:
      - solarize_network

  microservice-app:
    image: ghcr.io/projeto-de-extensao-grupo-06/schedule-notification:latest
    container_name: schedule-notification
    ports:
      - "${PORT_BACKEND_MICROSERVICE:-8082}:8080"
    env_file:
      - ../../../../schedule-notification/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://microservice-db:3306/schedule_notification_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    restart: on-failure
    depends_on:
      - microservice-db
    networks:
      - solarize_network

networks:
  solarize_network:
    name: solarize_network
    external: true