CREATE USER IF NOT EXISTS 'solarize'@'%' IDENTIFIED BY '06241234';
GRANT ALL PRIVILEGES ON *.* TO 'solarize'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

-- 1. Funcoes
CREATE FUNCTION IF NOT EXISTS unaccent(str TEXT) RETURNS TEXT DETERMINISTIC RETURN str COLLATE utf8mb4_unicode_ci;