version: "3.8"

services:
  backend-service:
    build:
      context: ../../springboot-web-backend
      dockerfile: Dockerfile
    platform: linux/amd64
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/solarize
      SPRING_DATASOURCE_USERNAME: solarize
      SPRING_DATASOURCE_PASSWORD: "06241234"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EMAIL: "dummy@email.com"
      PASSWORD_EMAIL: "dummy"
      SERVER_PORT: 8000
      BOT_SECRET: "solarize_whatsapp_bot_super_secret"
    ports:
      - "8000:8000"
    networks:
      - apps_network
      - storage_network

  frontend-service:
    build:
      context: ../../management-system
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    networks:
      - apps_network

  institutional-website:
    build:
      context: ../../institutional-website
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    networks:
      - apps_network

# TODO - lembrar de colocar o microserviço de schedule-notification do Fabrício


networks:
  apps_network:
    name: apps_network
    driver: bridge
  storage_network:
    external: true
    name: storage_network
