version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: bot-redis
    platform: linux/amd64
    command: redis-server --requirepass ${REDIS_PASSWORD:-default}
    environment:
      REDIS_USER: ${REDIS_USER:-default}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-default}
    ports:
      - "${PORT_BOT_REDIS:-6380}:6379"
    networks:
      - solarway_network

  waha:
    image: devlikeapro/waha:latest
    container_name: bot-waha
    platform: linux/amd64
    environment:
      WHATSAPP_HOOK_URL: http://bot-n8n:5678/webhook/webhook
      WHATSAPP_DEFAULT_ENGINE: GOWS
      WHATSAPP_HOOK_EVENTS: message
      WAHA_NO_API_KEY: true
      WAHA_DASHBOARD_NO_PASSWORD: true
      WHATSAPP_SWAGGER_NO_PASSWORD: true
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media
    ports:
      - "${PORT_WAHA:-3000}:3000"
    networks:
      - solarway_network

  n8n:
    build: 
      context: .
      dockerfile: ./n8n/Dockerfile
    container_name: bot-n8n
    platform: linux/amd64
    environment:
      BACKEND_API_URL: "${BACKEND_API_URL:-http://backend-service:8000}"
      WAHA_API_URL: "${WAHA_API_URL:-http://bot-waha:3000}"
      N8N_PROTOCOL: "${N8N_PROTOCOL:-http}"
      N8N_HOST: "${N8N_HOST:-localhost}"
      N8N_PORT: "${PORT_N8N:-5678}"
      N8N_PATH: "/"
      N8N_BASE_URL: "${N8N_BASE_URL:-http://localhost:5678/}"
      WEBHOOK_URL: "${N8N_WEBHOOK_URL:-http://localhost:5678/}"
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_LOG_LEVEL: debug
      N8N_SECURE_COOKIE: false
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
      BOT_SECRET: "${BOT_SECRET}"
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "${PORT_N8N:-5678}:5678"
    networks:
      - solarway_network

volumes:
  waha_sessions:
  waha_media:
  n8n_data:

networks:
  solarway_network:
    external: true
    name: solarway_network

