version: "3.8"

services:
  management-system:
    image: ghcr.io/projeto-de-extensao-grupo-06/management-system:latest
    container_name: management-system
    ports:
      - "${PORT_MANAGEMENT_SYSTEM:-8080}:3000"
    networks:
      - solarway_network

networks:
  solarway_network:
    name: solarway_network
    external: true
