version: "3.8"

services:
  redis:
    image: redis:7.4
    container_name: redis-multidb
    ports:
      - "${PORT_REDIS:-6379}:6379"
    command: [ "redis-server", "--databases", "3", "--save", "", "--appendonly", "no", "--maxmemory-policy", "allkeys-lru" ]
    restart: unless-stopped
    networks:
      - storage_network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: solarway
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PORT_MYSQL:-3307}:3306" # Exposta na porta configurada (padrão 3307)
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d # Scripts de inicialização
    restart: unless-stopped
    networks:
      - storage_network

networks:
  storage_network:
    driver: bridge
    name: storage_network
