version: "3.8"

services:
  backend-service:
    image: ghcr.io/projeto-de-extensao-grupo-06/springboot-web-backend:latest
    platform: linux/amd64
    container_name: backend-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST:-mysql-db}:3306/solarway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATA_REDIS_HOST: ${REDIS_HOST:-redis-multidb}
      SPRING_DATA_REDIS_PORT: 6379
      EMAIL: "${EMAIL}"
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
      SERVER_PORT: 8000
      BOT_SECRET: "${BOT_SECRET}"
      SOLARIZE_SECURITY_BOT_SECRET: "${BOT_SECRET}"
      BUCKET_NAME: "${BUCKET_NAME}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
    ports:
      - "${PORT_BACKEND_MONOLITH:-8000}:8000"
    restart: on-failure
    networks:
      - solarway_network
      - storage_network

networks:
  solarway_network:
    external: true
    name: solarway_network
  storage_network:
    external: true
    name: storage_network

